### ISSUE TITLE
Container Image build on WSL?

### ISSUE THREAD

**Issue by divingdiv** [ZenSepiol/Dear-ImGui-App-Framework#2]
Hi there, i am trying to build the docker image on a windows subsystem for linux based environment, and while trying to build the image using the mentioned commands under usage, in "readme.md" , the second command stating "sudo docker compose build" does not work for me,
It says docker has no command compose.
So was curious to know whether or not this dockerised image was ready to be built on windows subsystem for linux..

**Comment by ZenSepiol** [comment]
Hi, 
I have never tried it myself on WSL but as far as I know it should work. Maybe WSL is running the old docker compose. In that case, the command is named differently with an additional dash, `docker-compose` instead of `docker compose`. 
Or you need to install docker compose (it's a different tool additional to docker) on your WSL.

**Comment by divingdiv** [comment]
I don't think i have docker installed on my wsl, but now i have downloaded ubuntu, and am running ubuntu on dual boot with windows 10, just wanted to know now , how to build the docker image from here? If you know that , please help

**Comment by ZenSepiol** [comment]
If you run Ubuntu in your VM the following steps should be enough to use the docker: 
```
# Install docker
sudo snap install docker

# Prepare the image
sudo docker compose build

# Setup the build directory
sudo docker compose run console meson setup builddir /code --native-file=native.build

# Compile the application
sudo docker compose run console ninja -C builddir

# Run the application
sudo docker compose run gui builddir/app

# Run tests
sudo docker compose run console ninja -C builddir test
```

**Comment by divingdiv** [comment]
Thank you sdo much @ZenSepiol  for reverting back, i got it working on the day of raising this issue , sort of forgot  to check notifications on github. But nevertheless , thanks for the response, much appreciated.
