### ISSUE TITLE
xhost + glfw Error

### ISSUE THREAD

**Issue by g-tejas** [ZenSepiol/Dear-ImGui-App-Framework#3]
Hey,  i can't figure out why the docker compose run command won't run and i get this error,
Glfw Error 65544: X11: Failed to open display /private/tmp/com.apple.launchd.0NdV5Y47rv/org.xquartz:0
I have run the xhost + command and enabled connections from the xquartz settings but it still wont run, any idea why?

I am on a MacOS if that helps.

**Comment by ZenSepiol** [comment]
A few things that you might try: 
`xhost local:root`

Or it might be that you need to set the DISPLAY environment variable first by using:
`export DISPLAY='localhost:0.0'`

Unfortunately, I don't have a Mac so I can't verify. I'll ask around.
