### ISSUE TITLE
Readme has incorrect path to sample_app

### ISSUE THREAD

**Issue by mikeashbyseattle** [ZenSepiol/Dear-ImGui-App-Framework#5]
Under "Run the application" the path for the app when calling docker compose:
`docker compose run gui builddir/app/sample_app/sample_app`

does not exist.  There is an executable at: builddir/src/app/sample_app/sample_app

However, the following does not work: 
`docker compose run gui builddir/src/app/sample_app/sample_app`
Instead it results in: 
 glfw Error 65544: X11: Failed to open display :0

The good news is, the dockerized version compiles the samples (in the builddir/src/app/sample_app/sample_app) and they all work.

**Comment by ZenSepiol** [comment]
I've fixed the wrong path, thanks! 

Regarding the compose run, did you try running in your console ```xhost +``` before using ```docker compose run```?
